from pydantic import BaseModel
from typing import Optional, List

class References(BaseModel):
    "Structure of the responses"
    
    title: str = None
    summary: Optional[str] = None
    cited_text: Optional[str] = None
    context: str = None 

class Response(BaseModel):
    "The structure of the response generated by the model"
    response : str 
    references : List[References]


    
    